-- migrate:up
ALTER TABLE salary ADD COLUMN pension_account_id TEXT REFERENCES account(id) ON DELETE SET NULL;
ALTER TABLE salary ADD COLUMN kommun TEXT NOT NULL DEFAULT '';
ALTER TABLE salary ADD COLUMN forsamling TEXT NOT NULL DEFAULT '';
ALTER TABLE salary ADD COLUMN church_member BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE salary ADD COLUMN is_gross BOOLEAN NOT NULL DEFAULT FALSE;
