// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pdb

type Account struct {
	ID                    string
	Name                  string
	OwnerID               *string
	CreatedAt             int64
	UpdatedAt             int64
	BalanceUpperLimit     *float64
	CashFlowFrequency     *string
	CashFlowDestinationID *string
	TypeID                *string
	BudgetCategoryID      *string
}

type AccountSnapshot struct {
	AccountID string
	Date      int64
	Balance   string
}

type AccountType struct {
	ID    string
	Name  string
	Color *string
}

type ApiCache struct {
	CacheKey  string
	Value     string
	CreatedAt int64
}

type GrowthModel struct {
	ID               string
	AccountID        string
	ModelType        string
	AnnualGrowthRate string
	AnnualVolatility string
	StartDate        int64
	EndDate          *int64
	CreatedAt        int64
	UpdatedAt        int64
}

type Inkomstbasbelopp struct {
	ID        string
	Amount    float64
	ValidFrom int64
	CreatedAt int64
	UpdatedAt int64
}

type InvestmentRound struct {
	ID             string
	AccountID      string
	Date           int64
	Valuation      float64
	CreatedAt      int64
	UpdatedAt      int64
	PreMoneyShares float64
	Investment     float64
}

type Salary struct {
	ID               string
	Name             string
	ToAccountID      *string
	Priority         int64
	Recurrence       string
	BudgetCategoryID *string
	Enabled          bool
	CreatedAt        int64
	UpdatedAt        int64
	PensionAccountID *string
	Kommun           string
	Forsamling       string
	ChurchMember     bool
	IsGross          bool
}

type SalaryAmount struct {
	ID        string
	SalaryID  string
	Amount    string
	StartDate int64
	CreatedAt int64
	UpdatedAt int64
}

type ShareChange struct {
	ID          string
	AccountID   string
	Date        int64
	DeltaShares float64
	TotalPrice  float64
	CreatedAt   int64
	UpdatedAt   int64
}

type SpecialDate struct {
	ID    string
	Name  string
	Date  string
	Color *string
}

type StartupShareAccount struct {
	AccountID               string
	TaxRate                 float64
	ValuationDiscountFactor float64
}

type StartupShareOption struct {
	ID                  string
	AccountID           string
	SourceAccountID     string
	Shares              float64
	StrikePricePerShare float64
	GrantDate           int64
	EndDate             int64
	CreatedAt           int64
	UpdatedAt           int64
}

type TransferTemplate struct {
	ID               string
	Name             string
	FromAccountID    *string
	ToAccountID      *string
	AmountType       string
	AmountFixed      string
	AmountPercent    float64
	Priority         int64
	Recurrence       string
	StartDate        int64
	EndDate          *int64
	Enabled          bool
	CreatedAt        int64
	UpdatedAt        int64
	ParentTemplateID *string
	BudgetCategoryID *string
}

type TransferTemplateCategory struct {
	ID        string
	Name      string
	Color     *string
	CreatedAt int64
	UpdatedAt int64
}

type User struct {
	ID        string
	Name      string
	CreatedAt int64
	UpdatedAt int64
}
