// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pdb

import (
	"database/sql"
)

type Account struct {
	ID        string
	Name      string
	OwnerID   sql.NullString
	CreatedAt int64
	UpdatedAt int64
}

type AccountSnapshot struct {
	AccountID string
	Date      int64
	Balance   float64
}

type User struct {
	ID        string
	Name      string
	CreatedAt int64
	UpdatedAt int64
}
