// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pdb

type Account struct {
	ID                    string
	Name                  string
	OwnerID               *string
	CreatedAt             int64
	UpdatedAt             int64
	BalanceUpperLimit     *float64
	CashFlowFrequency     *string
	CashFlowDestinationID *string
	TypeID                *string
	BudgetCategoryID      *string
	IsIsk                 int64
}

type AccountSnapshot struct {
	AccountID string
	Date      int64
	Balance   string
}

type AccountType struct {
	ID    string
	Name  string
	Color *string
}

type ApiCache struct {
	CacheKey  string
	Value     string
	CreatedAt int64
}

type AppSetting struct {
	Key   string
	Value string
}

type Bill struct {
	ID               string
	BillAccountID    string
	Name             string
	BudgetCategoryID *string
	Enabled          bool
	Notes            string
	Url              string
	CreatedAt        int64
	UpdatedAt        int64
}

type BillAccount struct {
	ID            string
	Name          string
	FromAccountID *string
	Recurrence    string
	Priority      int64
	Enabled       bool
	CreatedAt     int64
	UpdatedAt     int64
}

type BillAmount struct {
	ID        string
	BillID    string
	Amount    string
	StartDate int64
	EndDate   *int64
	CreatedAt int64
	UpdatedAt int64
	Period    string
	Currency  string
}

type FaviconCache struct {
	Domain      string
	IconData    []byte
	ContentType string
	CreatedAt   int64
}

type ForecastCache struct {
	Date          int64
	AccountTypeID string
	Median        float64
	LowerBound    float64
	UpperBound    float64
}

type FullParentalLeave struct {
	ID              string
	SalaryID        string
	StartDate       int64
	EndDate         int64
	SjukDaysPerWeek float64
	CreatedAt       int64
	UpdatedAt       int64
}

type GrowthModel struct {
	ID               string
	AccountID        string
	ModelType        string
	AnnualGrowthRate string
	AnnualVolatility string
	StartDate        int64
	EndDate          *int64
	CreatedAt        int64
	UpdatedAt        int64
}

type InvestmentRound struct {
	ID             string
	AccountID      string
	Date           int64
	Valuation      float64
	CreatedAt      int64
	UpdatedAt      int64
	PreMoneyShares float64
	Investment     float64
}

type PartialParentalLeave struct {
	ID                     string
	SalaryID               string
	StartDate              int64
	EndDate                int64
	SjukDaysPerYear        float64
	LagstaDaysPerYear      float64
	SkippedWorkDaysPerYear float64
	CreatedAt              int64
	UpdatedAt              int64
}

type Salary struct {
	ID               string
	Name             string
	ToAccountID      *string
	Priority         int64
	Recurrence       string
	BudgetCategoryID *string
	Enabled          bool
	CreatedAt        int64
	UpdatedAt        int64
	PensionAccountID *string
	Kommun           string
	Forsamling       string
	ChurchMember     bool
	IsGross          bool
}

type SalaryAdjustment struct {
	ID                   string
	SalaryID             string
	ValidFrom            int64
	VacationDaysPerYear  float64
	SickDaysPerOccasion  float64
	SickOccasionsPerYear float64
	VabDaysPerYear       float64
	CreatedAt            int64
	UpdatedAt            int64
}

type SalaryAmount struct {
	ID        string
	SalaryID  string
	Amount    string
	StartDate int64
	CreatedAt int64
	UpdatedAt int64
}

type ShareChange struct {
	ID          string
	AccountID   string
	Date        int64
	DeltaShares float64
	TotalPrice  float64
	CreatedAt   int64
	UpdatedAt   int64
}

type SpecialDate struct {
	ID    string
	Name  string
	Date  string
	Color *string
}

type StartupShareAccount struct {
	AccountID               string
	TaxRate                 float64
	ValuationDiscountFactor float64
}

type StartupShareOption struct {
	ID                  string
	AccountID           string
	SourceAccountID     string
	Shares              float64
	StrikePricePerShare float64
	GrantDate           int64
	EndDate             int64
	CreatedAt           int64
	UpdatedAt           int64
}

type SweYearlyParam struct {
	ID            string
	Amount        float64
	ValidFrom     int64
	CreatedAt     int64
	UpdatedAt     int64
	Prisbasbelopp float64
	SchablonRanta float64
	IskFribelopp  float64
}

type TransferTemplate struct {
	ID               string
	Name             string
	FromAccountID    *string
	ToAccountID      *string
	AmountType       string
	AmountFixed      string
	AmountPercent    float64
	Priority         int64
	Recurrence       string
	StartDate        int64
	EndDate          *int64
	Enabled          bool
	CreatedAt        int64
	UpdatedAt        int64
	BudgetCategoryID *string
}

type TransferTemplateCategory struct {
	ID        string
	Name      string
	Color     *string
	CreatedAt int64
	UpdatedAt int64
}

type User struct {
	ID        string
	Name      string
	CreatedAt int64
	UpdatedAt int64
}
