// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: parental_leave.sql

package pdb

import (
	"context"
)

const deleteFullParentalLeave = `-- name: DeleteFullParentalLeave :exec
DELETE FROM full_parental_leave
WHERE id = ?
`

func (q *Queries) DeleteFullParentalLeave(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFullParentalLeave, id)
	return err
}

const deletePartialParentalLeave = `-- name: DeletePartialParentalLeave :exec
DELETE FROM partial_parental_leave
WHERE id = ?
`

func (q *Queries) DeletePartialParentalLeave(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePartialParentalLeave, id)
	return err
}

const listAllFullParentalLeaves = `-- name: ListAllFullParentalLeaves :many
SELECT id, salary_id, start_date, end_date, sjuk_days_per_week, created_at, updated_at
FROM full_parental_leave
ORDER BY salary_id, start_date, id
`

func (q *Queries) ListAllFullParentalLeaves(ctx context.Context) ([]FullParentalLeave, error) {
	rows, err := q.db.QueryContext(ctx, listAllFullParentalLeaves)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FullParentalLeave
	for rows.Next() {
		var i FullParentalLeave
		if err := rows.Scan(
			&i.ID,
			&i.SalaryID,
			&i.StartDate,
			&i.EndDate,
			&i.SjukDaysPerWeek,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPartialParentalLeaves = `-- name: ListAllPartialParentalLeaves :many
SELECT id, salary_id, start_date, end_date, sjuk_days_per_year, lagsta_days_per_year, skipped_work_days_per_year, created_at, updated_at
FROM partial_parental_leave
ORDER BY salary_id, start_date, id
`

func (q *Queries) ListAllPartialParentalLeaves(ctx context.Context) ([]PartialParentalLeave, error) {
	rows, err := q.db.QueryContext(ctx, listAllPartialParentalLeaves)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartialParentalLeave
	for rows.Next() {
		var i PartialParentalLeave
		if err := rows.Scan(
			&i.ID,
			&i.SalaryID,
			&i.StartDate,
			&i.EndDate,
			&i.SjukDaysPerYear,
			&i.LagstaDaysPerYear,
			&i.SkippedWorkDaysPerYear,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFullParentalLeaves = `-- name: ListFullParentalLeaves :many
SELECT id, salary_id, start_date, end_date, sjuk_days_per_week, created_at, updated_at
FROM full_parental_leave
WHERE salary_id = ?
ORDER BY start_date, id
`

func (q *Queries) ListFullParentalLeaves(ctx context.Context, salaryID string) ([]FullParentalLeave, error) {
	rows, err := q.db.QueryContext(ctx, listFullParentalLeaves, salaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FullParentalLeave
	for rows.Next() {
		var i FullParentalLeave
		if err := rows.Scan(
			&i.ID,
			&i.SalaryID,
			&i.StartDate,
			&i.EndDate,
			&i.SjukDaysPerWeek,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartialParentalLeaves = `-- name: ListPartialParentalLeaves :many
SELECT id, salary_id, start_date, end_date, sjuk_days_per_year, lagsta_days_per_year, skipped_work_days_per_year, created_at, updated_at
FROM partial_parental_leave
WHERE salary_id = ?
ORDER BY start_date, id
`

func (q *Queries) ListPartialParentalLeaves(ctx context.Context, salaryID string) ([]PartialParentalLeave, error) {
	rows, err := q.db.QueryContext(ctx, listPartialParentalLeaves, salaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartialParentalLeave
	for rows.Next() {
		var i PartialParentalLeave
		if err := rows.Scan(
			&i.ID,
			&i.SalaryID,
			&i.StartDate,
			&i.EndDate,
			&i.SjukDaysPerYear,
			&i.LagstaDaysPerYear,
			&i.SkippedWorkDaysPerYear,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFullParentalLeave = `-- name: UpsertFullParentalLeave :one
INSERT INTO full_parental_leave (
    id,
    salary_id,
    start_date,
    end_date,
    sjuk_days_per_week,
    created_at,
    updated_at
  )
VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT (id) DO
UPDATE
SET salary_id = EXCLUDED.salary_id,
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date,
  sjuk_days_per_week = EXCLUDED.sjuk_days_per_week,
  updated_at = EXCLUDED.updated_at
RETURNING id, salary_id, start_date, end_date, sjuk_days_per_week, created_at, updated_at
`

type UpsertFullParentalLeaveParams struct {
	ID              string
	SalaryID        string
	StartDate       int64
	EndDate         int64
	SjukDaysPerWeek float64
	CreatedAt       int64
	UpdatedAt       int64
}

func (q *Queries) UpsertFullParentalLeave(ctx context.Context, arg UpsertFullParentalLeaveParams) (FullParentalLeave, error) {
	row := q.db.QueryRowContext(ctx, upsertFullParentalLeave,
		arg.ID,
		arg.SalaryID,
		arg.StartDate,
		arg.EndDate,
		arg.SjukDaysPerWeek,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i FullParentalLeave
	err := row.Scan(
		&i.ID,
		&i.SalaryID,
		&i.StartDate,
		&i.EndDate,
		&i.SjukDaysPerWeek,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPartialParentalLeave = `-- name: UpsertPartialParentalLeave :one
INSERT INTO partial_parental_leave (
    id,
    salary_id,
    start_date,
    end_date,
    sjuk_days_per_year,
    lagsta_days_per_year,
    skipped_work_days_per_year,
    created_at,
    updated_at
  )
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (id) DO
UPDATE
SET salary_id = EXCLUDED.salary_id,
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date,
  sjuk_days_per_year = EXCLUDED.sjuk_days_per_year,
  lagsta_days_per_year = EXCLUDED.lagsta_days_per_year,
  skipped_work_days_per_year = EXCLUDED.skipped_work_days_per_year,
  updated_at = EXCLUDED.updated_at
RETURNING id, salary_id, start_date, end_date, sjuk_days_per_year, lagsta_days_per_year, skipped_work_days_per_year, created_at, updated_at
`

type UpsertPartialParentalLeaveParams struct {
	ID                     string
	SalaryID               string
	StartDate              int64
	EndDate                int64
	SjukDaysPerYear        float64
	LagstaDaysPerYear      float64
	SkippedWorkDaysPerYear float64
	CreatedAt              int64
	UpdatedAt              int64
}

func (q *Queries) UpsertPartialParentalLeave(ctx context.Context, arg UpsertPartialParentalLeaveParams) (PartialParentalLeave, error) {
	row := q.db.QueryRowContext(ctx, upsertPartialParentalLeave,
		arg.ID,
		arg.SalaryID,
		arg.StartDate,
		arg.EndDate,
		arg.SjukDaysPerYear,
		arg.LagstaDaysPerYear,
		arg.SkippedWorkDaysPerYear,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PartialParentalLeave
	err := row.Scan(
		&i.ID,
		&i.SalaryID,
		&i.StartDate,
		&i.EndDate,
		&i.SjukDaysPerYear,
		&i.LagstaDaysPerYear,
		&i.SkippedWorkDaysPerYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
