// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: salary.sql

package pdb

import (
	"context"
)

const deleteSalary = `-- name: DeleteSalary :exec
DELETE FROM salary
WHERE id = ?
`

func (q *Queries) DeleteSalary(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSalary, id)
	return err
}

const deleteSalaryAmount = `-- name: DeleteSalaryAmount :exec
DELETE FROM salary_amount
WHERE id = ?
`

func (q *Queries) DeleteSalaryAmount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSalaryAmount, id)
	return err
}

const getSalary = `-- name: GetSalary :one
SELECT id, name, to_account_id, priority, recurrence, budget_category_id, enabled, created_at, updated_at
FROM salary
WHERE id = ?
`

func (q *Queries) GetSalary(ctx context.Context, id string) (Salary, error) {
	row := q.db.QueryRowContext(ctx, getSalary, id)
	var i Salary
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ToAccountID,
		&i.Priority,
		&i.Recurrence,
		&i.BudgetCategoryID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSalaryAmount = `-- name: GetSalaryAmount :one
SELECT id, salary_id, amount, start_date, created_at, updated_at
FROM salary_amount
WHERE id = ?
`

func (q *Queries) GetSalaryAmount(ctx context.Context, id string) (SalaryAmount, error) {
	row := q.db.QueryRowContext(ctx, getSalaryAmount, id)
	var i SalaryAmount
	err := row.Scan(
		&i.ID,
		&i.SalaryID,
		&i.Amount,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllSalaryAmounts = `-- name: ListAllSalaryAmounts :many
SELECT id, salary_id, amount, start_date, created_at, updated_at
FROM salary_amount
ORDER BY salary_id, start_date, id
`

func (q *Queries) ListAllSalaryAmounts(ctx context.Context) ([]SalaryAmount, error) {
	rows, err := q.db.QueryContext(ctx, listAllSalaryAmounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalaryAmount
	for rows.Next() {
		var i SalaryAmount
		if err := rows.Scan(
			&i.ID,
			&i.SalaryID,
			&i.Amount,
			&i.StartDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalaries = `-- name: ListSalaries :many
SELECT id, name, to_account_id, priority, recurrence, budget_category_id, enabled, created_at, updated_at
FROM salary
ORDER BY name, id
`

func (q *Queries) ListSalaries(ctx context.Context) ([]Salary, error) {
	rows, err := q.db.QueryContext(ctx, listSalaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Salary
	for rows.Next() {
		var i Salary
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ToAccountID,
			&i.Priority,
			&i.Recurrence,
			&i.BudgetCategoryID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalaryAmounts = `-- name: ListSalaryAmounts :many
SELECT id, salary_id, amount, start_date, created_at, updated_at
FROM salary_amount
WHERE salary_id = ?
ORDER BY start_date, id
`

func (q *Queries) ListSalaryAmounts(ctx context.Context, salaryID string) ([]SalaryAmount, error) {
	rows, err := q.db.QueryContext(ctx, listSalaryAmounts, salaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalaryAmount
	for rows.Next() {
		var i SalaryAmount
		if err := rows.Scan(
			&i.ID,
			&i.SalaryID,
			&i.Amount,
			&i.StartDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSalary = `-- name: UpsertSalary :one
INSERT INTO salary (
    id,
    name,
    to_account_id,
    priority,
    recurrence,
    budget_category_id,
    enabled,
    created_at,
    updated_at
  )
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (id) DO
UPDATE
SET name = EXCLUDED.name,
  to_account_id = EXCLUDED.to_account_id,
  priority = EXCLUDED.priority,
  recurrence = EXCLUDED.recurrence,
  budget_category_id = EXCLUDED.budget_category_id,
  enabled = EXCLUDED.enabled,
  updated_at = EXCLUDED.updated_at
RETURNING id, name, to_account_id, priority, recurrence, budget_category_id, enabled, created_at, updated_at
`

type UpsertSalaryParams struct {
	ID               string
	Name             string
	ToAccountID      *string
	Priority         int64
	Recurrence       string
	BudgetCategoryID *string
	Enabled          bool
	CreatedAt        int64
	UpdatedAt        int64
}

func (q *Queries) UpsertSalary(ctx context.Context, arg UpsertSalaryParams) (Salary, error) {
	row := q.db.QueryRowContext(ctx, upsertSalary,
		arg.ID,
		arg.Name,
		arg.ToAccountID,
		arg.Priority,
		arg.Recurrence,
		arg.BudgetCategoryID,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Salary
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ToAccountID,
		&i.Priority,
		&i.Recurrence,
		&i.BudgetCategoryID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSalaryAmount = `-- name: UpsertSalaryAmount :one
INSERT INTO salary_amount (
    id,
    salary_id,
    amount,
    start_date,
    created_at,
    updated_at
  )
VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT (id) DO
UPDATE
SET salary_id = EXCLUDED.salary_id,
  amount = EXCLUDED.amount,
  start_date = EXCLUDED.start_date,
  updated_at = EXCLUDED.updated_at
RETURNING id, salary_id, amount, start_date, created_at, updated_at
`

type UpsertSalaryAmountParams struct {
	ID        string
	SalaryID  string
	Amount    string
	StartDate int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) UpsertSalaryAmount(ctx context.Context, arg UpsertSalaryAmountParams) (SalaryAmount, error) {
	row := q.db.QueryRowContext(ctx, upsertSalaryAmount,
		arg.ID,
		arg.SalaryID,
		arg.Amount,
		arg.StartDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SalaryAmount
	err := row.Scan(
		&i.ID,
		&i.SalaryID,
		&i.Amount,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
